server:
  port: 8081
#数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/crm2?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    password: "123456"
    username: root
#热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

#mybatis配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.yejian.bean
  configuration:
    map-underscore-to-camel-case: true

#pageHelper分页
pagehelper:
  helper-dialect: mysql

#设置dao日志打印级别
logging:
  level:
    com:
      yejian:
        mapper: debug

#图片上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  resources:
    static-locations: classpath:src/main/resources/pic